CREATE TABLE IF NOT EXISTS `cliente` (
  `CD_CLIENTE` int(11) NOT NULL AUTO_INCREMENT,
  `NM_CLIENTE` varchar(50) NOT NULL,
  `NR_FONE` varchar(14) DEFAULT NULL,
  `DT_CADASTRO` datetime DEFAULT current_timestamp(),
  `ST_ATIVO` varchar(3) DEFAULT 'SIM',
  PRIMARY KEY (`CD_CLIENTE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

CREATE TABLE IF NOT EXISTS `comissaoparcela` (
  `CD_COMISSAOPARCELA` int(11) NOT NULL AUTO_INCREMENT,
  `NR_PARCELA` int(11) NOT NULL,
  `PC_COMISSAO` decimal(20,6) NOT NULL,
  `VL_COMISSAO` decimal(20,6) NOT NULL,
  `CD_CRM` int(11) NOT NULL,
  `CD_FAIXACOMISSAO` int(11) NOT NULL,
  `CD_FUNCIONARIO` int(11) NOT NULL,
  `CD_CLIENTE` int(11) NOT NULL,
  `TP_PARCELA` varchar(1) NOT NULL,
  `DT_CADASTRO` datetime NOT NULL DEFAULT current_timestamp(),
  `NR_MESPAGAMENTO` int(11) NOT NULL,
  `NR_ANOPAGAMENTO` int(11) NOT NULL,
  `DT_PAGAMENTO` int(11) NOT NULL,
  PRIMARY KEY (`CD_COMISSAOPARCELA`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

CREATE TABLE IF NOT EXISTS `crm` (
  `CD_CRM` int(11) NOT NULL AUTO_INCREMENT,
  `CD_CLIENTE` int(11) NOT NULL,
  `CD_STATUS` int(11) NOT NULL DEFAULT 0,
  `DS_OBS` varchar(500) DEFAULT '',
  `DT_CADASTRO` datetime NOT NULL DEFAULT current_timestamp(),
  `CD_FUNCIONARIO` int(11) NOT NULL,
  `VL_CREDITO` decimal(20,6) NOT NULL,
  `DT_ATUALIZACAO` datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `CD_FAIXACOMISSAO` int(11) NOT NULL,
  `TP_PARCELA` varchar(1) DEFAULT NULL,
  PRIMARY KEY (`CD_CRM`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

CREATE TABLE IF NOT EXISTS `empresa` (
  `NR_CPFCNPJ` varchar(14) NOT NULL DEFAULT ''
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

CREATE TABLE IF NOT EXISTS `faixacomissao` (
  `CD_FAIXACOMISSAO` int(11) NOT NULL AUTO_INCREMENT,
  `DS_FAIXACOMISSAO` varchar(50) NOT NULL,
  `NR_PARCELAS` int(11) NOT NULL DEFAULT 0,
  `VL_MINIMO` decimal(20,6) NOT NULL DEFAULT 0.000000,
  `VL_MAXIMO` decimal(20,6) NOT NULL DEFAULT 0.000000,
  `DT_CADASTRO` datetime NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`CD_FAIXACOMISSAO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

CREATE TABLE IF NOT EXISTS `faixacomissaoparcela` (
  `CD_FAIXACOMISSAOPARCELA` int(11) NOT NULL AUTO_INCREMENT,
  `CD_FAIXACOMISSAO` int(11) NOT NULL,
  `NR_PARCELA` int(11) NOT NULL,
  `PC_COMISSAO` decimal(20,6) NOT NULL DEFAULT 0.000000,
  `TP_PARCELA` char(1) NOT NULL,
  PRIMARY KEY (`CD_FAIXACOMISSAOPARCELA`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

CREATE TABLE IF NOT EXISTS `funcionario` (
  `CD_FUNCIONARIO` int(11) NOT NULL AUTO_INCREMENT,
  `NM_FUNCIONARIO` varchar(50) NOT NULL,
  `DT_CADASTRO` datetime DEFAULT current_timestamp(),
  `ST_ATIVO` varchar(3) NOT NULL DEFAULT 'SIM',
  PRIMARY KEY (`CD_FUNCIONARIO`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;